# Generated by Django 6.0.5 on 2026-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('project_type', models.CharField(blank=True, choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('ai', 'AI / Machine Learning'), ('cyber', 'Cybersecurity'), ('api', 'API Development'), ('other', 'Other')], max_length=50, null=True)),
                ('budget', models.CharField(blank=True, choices=[('low', 'Under 100,000 ETB'), ('mid', '100,000 - 300,000 ETB'), ('high', '300,000 - 600,000 ETB'), ('enterprise', '600,000+ ETB')], max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
